[theme]
primaryColor = "#002D72"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
